name: CPP Semver CI
on: [push, pull_request]

jobs:
  unix:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build_type: [Debug, Release]
        os: [macos-latest, ubuntu-latest]
        compiler: [g++, clang++]
        flags: [-std=c++17, -std=c++20]
    name: ${{matrix.os}} (${{matrix.compiler}} ${{matrix.build_type}})
    env:
      CXX: ${{ matrix.compiler }}
      CXXFLAGS: ${{ matrix.flags }}
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{matrix.build_type}} -DSEMVER_BUILD_TESTS=ON
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build; ctest -C ${{matrix.build_type}} -j 10

  windows:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        os: [ windows-latest ]
        flags: [ "/std:c++11", "/std:c++latest" ]
    name: ${{matrix.os}} ${{matrix.build_type}})
    env:
      CXXFLAGS: ${{ matrix.flags }}
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{matrix.build_type}} -DSEMVER_BUILD_TESTS=ON
    - name: build
      run: cmake --build build --parallel 10
    - name: test
      run: cd build; ctest -C ${{matrix.build_type}} -j 10


