name: CPP Semver Sanitize
on: [push, pull_request]

jobs:
  sanitize:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        compiler: [ clang++ ]
        flags:
          - "-fsanitize=leak -fno-omit-frame-pointer"       #LSAN
          - "-fsanitize=address -fno-omit-frame-pointer"    #ASAN
          - "-fsanitize=memory -fno-omit-frame-pointer"     #MSAN
          - "-fsanitize=thread -fno-omit-frame-pointer"     #TSAN
          - "-fsanitize=undefined -fno-omit-frame-pointer"  #UBSAN
    name: ${{matrix.os}} ${{matrix.compiler}} ${{matrix.build}} ${{matrix.flags}}
    env:
      CXX: ${{ matrix.compiler }}
      CXXFLAGS: ${{ matrix.flags }}
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake -S . -B build -DSEMVER_BUILD_TESTS=ON
    - name: build
      run: cmake --build build --parallel 4
    - name: test
      working-directory: build
      run: ctest -j4