
name: "PR Checks"
on: [pull_request]
jobs:
  verify-pr:
    name: "Verify PR title and desc"
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout ops-shared
        uses: actions/checkout@v2
        with:
          repository: Twingate/ops-shared
          token: ${{ secrets.DANGER_GITHUB_ACCESS_TOKEN }}
          path: ops-shared
      - name: Danger
        uses: danger/danger-js@9.1.6
        with:
          args: "--failOnErrors --dangerfile ops-shared/pr_check/dangerfile.pr.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true
